In [1]:
# Mutable Data Type Example (List)
my_list = [1, 2, 3]
print("Original List:", my_list)
# Modifying the list (changing contents)
my_list.append(4)
print("Modified List:", my_list)
# Immutable Data Type Example (Tuple)
my_tuple = (1, 2, 3)
print("Original Tuple:", my_tuple)

Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)


In [2]:
age = 23 #int
pi = 3.14 #float
temperature = -5.5 #float
print("data type of variable age = ", type(age))
print("data type of variable pi = ", type(pi))
print("data type of variable temperature = ", type(temperature))

data type of variable age =  <class 'int'>
data type of variable pi =  <class 'float'>
data type of variable temperature =  <class 'float'>


In [4]:
name = "Alice"
greeting = "Hello"
address = "123 Main St"
print("data type of the variable name = ",type(name))
print("data type of the variable greeting = ",type(greeting))
print("data type of the variable address = ",type(address))
# slice only one element
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])
# slice a range of elements
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])

data type of the variable name =  <class 'str'>
data type of the variable greeting =  <class 'str'>
data type of the variable address =  <class 'str'>
The first letter of the name is: A
The last letter of the name is: e
The second letter to the fourth of the name is: lic
The first two letters of the name are: Al
Substring starting from the third letter is: ice


In [5]:
list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]
# List is mutable
mixed_list[0] = False
mixed_list

[False, 'Hello', True]

In [8]:
colors = ("red", "green", "yellow", "blue")
print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])

# To modify a 'tuple', it must first be converted to a mutable type like a list.
# Then, modifications can be made to the list, and it can be converted back to a tuple if desired.
colors_list = list(colors)
colors_list[0] = "purple" # Modifying the list
colors = tuple(colors_list) # Converting back to a tuple

print("Modified colors tuple:", colors)

First element: red
Last two elements: ('yellow', 'blue')
Middle two elements: ('green', 'yellow')
Modified colors tuple: ('purple', 'green', 'yellow', 'blue')


In [10]:
person = {'name':'John','age':30,'city':'Pittsburgh'}
print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live at {
person['city']}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

Hello my name is John. I am 30 years old and I live at Pittsburgh.
All keys: ['name', 'age', 'city']
All values: ['John', 30, 'Pittsburgh']


In [11]:
unique_numbers = {1,2,3,3,3,3,4,5}
print(unique_numbers)

{1, 2, 3, 4, 5}


In [13]:
is_student = True
has_license = False
print("data type of the variable is_student = ",type(is_student))
print("data type of the variable has_license = ",type(has_license))

data type of the variable is_student =  <class 'bool'>
data type of the variable has_license =  <class 'bool'>


In [14]:
result = None

Logical Statement

In [16]:
num = 10
if num > 0:
    print("Positive")
elif num == 0:
    print("Zero")

Positive


In [18]:
x = 5
y = 10
if x > 0 and y < 20:
    print("Both conditions are true")
if x > 0 or y > 20:
    print("At least one condition is true")
if not x == 0:
    print("x is not equal to 0")

Both conditions are true
At least one condition is true
x is not equal to 0


In [20]:
# Define two boolean variables
a = True
b = False
# Using the ’and’ operator
if a and b:
    print("Both a and b are True")
else:
    print("Either a or b is False") # This will be printed
# Using the ’or’ operator
if a or b:
    print("At least one of a or b is True") # This will be printed
else:
    print("Both a and b are False")
# Using the ’not’ operator
if not a:
    print("a is False") # This will not be printed
else:
    print("a is True") # This will be printed

Either a or b is False
At least one of a or b is True
a is True


Loops

In [22]:
# for loop:
fruits = ["apple", "banana","cherry"]
for fruit in fruits:
    print(fruit)
# While loop:
count = 0
while count < 5:
    print("Count is:", count)
    count += 1
# Break
fruits = ["apple", "banana", "orange"]
print("loop 1")
for fruit in fruits:
    print(fruit)
    if fruit == "apple":
        break
# Continue
print("loop 2")
for fruit in fruits:
    if fruit == "apple":
        continue
    else:
        print(fruit)

apple
banana
cherry
Count is: 0
Count is: 1
Count is: 2
Count is: 3
Count is: 4
loop 1
apple
loop 2
banana
orange


Function

In [24]:
def add_binary(a, b):
    '''
    Returns the sum of two decimal numbers in binary digits.
    Parameters:
    a (int): A decimal integer
    b (int): Another decimal integer
    Returns:
    binary_sum (str): Binary string of the sum of a and b
    '''
    binary_sum = bin(a+b)[2:]
    return binary_sum

In [25]:
print("Hello, World!") # Output: Hello, World!
length = len("Hello") # Output: 5
data_type = type(42) # Output: <class ’int’>
total = sum([1, 2, 3]) # Output: 6

Hello, World!


In [27]:
# str.upper(): Converts all characters in a string to uppercase.
message = "hello".upper() # Output: "HELLO"
# list.append(): Adds an element to the end of a list.
fruits = ["apple", "banana"]
fruits.append("cherry") # Output: ["apple", "banana", "cherry"]
# dict.get(): Returns the value associated with a key in a dictionary.
info = {"name": "Alice", "age": 25}
age = info.get("age") # Output: 25

In [29]:
def temperature_converter():
    """
    Converts temperature between Celsius and Fahrenheit.
    This function prompts the user to specify the conversion type (Celsius to Fahrenheit or
    Fahrenheit to Celsius)
    and then asks for the temperature value. It calculates and returns the converted temperature.
    Returns:
    float: The converted temperature value.
    """
    print("Choose conversion type:")
    print("1. Celsius to Fahrenheit")
    print("2. Fahrenheit to Celsius")
    # Get conversion choice from user
    choice = input("Enter 1 or 2: ")
    if choice == "1":
    # Celsius to Fahrenheit conversion
        celsius = float(input("Enter temperature in Celsius: "))
        fahrenheit = (celsius * 9/5) + 32
        print(f"{celsius}C is equal to {fahrenheit}F")
        return fahrenheit
    elif choice == "2":
    # Fahrenheit to Celsius conversion
        fahrenheit = float(input("Enter temperature in Fahrenheit: "))
        celsius = (fahrenheit - 32) * 5/9
        print(f"{fahrenheit}F is equal to {celsius}C")
        return celsius
    else:
        print("Invalid choice. Please enter 1 or 2.")
        return None
# Call the function
temperature_converter()

Choose conversion type:
1. Celsius to Fahrenheit
2. Fahrenheit to Celsius
Enter 1 or 2: 1
Enter temperature in Celsius: 20
20.0C is equal to 68.0F


68.0

Global and Local Varables

In [31]:
x = 10 # Global Variable.
def print_global():
    print(x) # Accessing global variable
print_global() # Output: 10

10


In [33]:
def print_local():
    y = 5 # Local variable
    print(y)
print_local() # Output: 5
# print(y) # This would cause an error because y is not accessible outside the function

5


In [35]:
x = 10 # Global variable
def modify_global():
    global x # Declaring x as global
    x = 20 # Modifying global x
modify_global()
print(x) # Output: 20

20


To Do Task

In [36]:
def convert_units(conversion_type, value):
    """
    Converts units based on the selected conversion type.

    Parameters:
    conversion_type (int): The type of conversion selected by the user.
                           1 = meters to feet
                           2 = feet to meters
                           3 = kilograms to pounds
                           4 = pounds to kilograms
                           5 = liters to gallons
                           6 = gallons to liters
    value (float): The numerical value to convert.

    Returns:
    float: The converted value.
    """

    if conversion_type == 1:
        return value * 3.28084   # meters to feet
    elif conversion_type == 2:
        return value / 3.28084   # feet to meters
    elif conversion_type == 3:
        return value * 2.20462   # kg to pounds
    elif conversion_type == 4:
        return value / 2.20462   # pounds to kg
    elif conversion_type == 5:
        return value * 0.264172  # liters to gallons
    elif conversion_type == 6:
        return value / 0.264172  # gallons to liters
    else:
        return None


try:
    print("Unit Conversion Program")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    print("3. Kilograms to Pounds")
    print("4. Pounds to Kilograms")
    print("5. Liters to Gallons")
    print("6. Gallons to Liters")

    choice = int(input("Choose conversion type (1-6): "))
    value = float(input("Enter the value to convert: "))

    result = convert_units(choice, value)

    if result is None:
        print("Invalid conversion type selected.")
    else:
        print("Converted value:", round(result, 2))

except ValueError:
    print("Error: Please enter a valid numeric value.")
except Exception as e:
    print("Unexpected error:", e)

Unit Conversion Program
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Choose conversion type (1-6): 1
Enter the value to convert: 20
Converted value: 65.62


In [37]:
def find_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)


def find_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The average of the numbers.
    """
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The maximum number in the list.
    """
    return max(numbers)


def find_min(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values.

    Returns:
    float: The minimum number in the list.
    """
    return min(numbers)


try:
    print("Mathematical Operations Program")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = int(input("Choose an operation (1-4): "))

    user_input = input("Enter numbers separated by spaces: ")

    numbers = [float(num) for num in user_input.split()]

    if len(numbers) == 0:
        raise ValueError("List cannot be empty.")

    if choice == 1:
        print("Sum =", find_sum(numbers))
    elif choice == 2:
        print("Average =", find_average(numbers))
    elif choice == 3:
        print("Maximum =", find_max(numbers))
    elif choice == 4:
        print("Minimum =", find_min(numbers))
    else:
        print("Invalid operation selected.")

except ValueError:
    print("Error: Please enter valid numeric values.")
except Exception as e:
    print("Unexpected error:", e)

Mathematical Operations Program
1. Sum
2. Average
3. Maximum
4. Minimum
Choose an operation (1-4): 1
Enter numbers separated by spaces: 5
Sum = 5.0


Exercise on List Manipulation:

In [38]:
#1. Extract Every Other Element:
def extract_every_other(lst):
    """
    Extracts every other element from a list starting from the first element.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every other element.
    """
    return lst[::2]


numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)

print("Original list:", numbers)
print("Every other element:", result)

Original list: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]


In [39]:
#2. Slice a Sublist:
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list from start index to end index (inclusive).

    Parameters:
    lst (list): The original list.
    start (int): Starting index.
    end (int): Ending index.

    Returns:
    list: Sublist from start to end (inclusive).
    """
    return lst[start:end+1]


numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)

print("Original list:", numbers)
print("Sublist:", result)


Original list: [1, 2, 3, 4, 5, 6]
Sublist: [3, 4, 5]


In [45]:
#3. Reverse a List Using Slicing:
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Parameters:
    lst (list): The original list.

    Returns:
    list: The reversed list.
    """
    return lst[::-1]

numbers = [1, 2, 3, 4, 5]
result = reverse_list(numbers)

print("Original list:", numbers)
print("Reversed list:", result)

Original list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]


In [46]:
#4. Remove the First and Last Elements:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list and returns the resulting sublist.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list without the first and last elements.
    """
    return lst[1:-1]


# Input list
numbers = [1, 2, 3, 4, 5]

# Function call
result = remove_first_last(numbers)

# Display result
print("Original list:", numbers)
print("Resulting list:", result)

Original list: [1, 2, 3, 4, 5]
Resulting list: [2, 3, 4]


In [47]:
#5. Get the First n Elements:
def get_first_n(lst, n):
    """
    Returns the first n elements of a list using slicing.

    Parameters:
    lst (list): The input list.
    n (int): Number of elements to extract from the beginning.

    Returns:
    list: A list containing the first n elements.
    """
    return lst[:n]


numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 3)

print("Original list:", numbers)
print("First n elements:", result)

Original list: [1, 2, 3, 4, 5]
First n elements: [1, 2, 3]


In [48]:
#6. Extract Elements from the End:
def get_last_n(lst, n):
    """
    Returns the last n elements of a list using slicing.

    Parameters:
    lst (list): The input list.
    n (int): Number of elements to extract from the end.

    Returns:
    list: A list containing the last n elements.
    """
    return lst[-n:]

numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)

print("Original list:", numbers)
print("Last n elements:", result)

Original list: [1, 2, 3, 4, 5]
Last n elements: [4, 5]


In [49]:
#7. Extract Elements in Reverse Order:
def reverse_skip(lst):
    """
    Extracts every second element from a list in reverse order,
    starting from the second-to-last element.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A list containing every second element in reverse order
          starting from the second-to-last.
    """
    return lst[-2::-2]

numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)

print("Original list:", numbers)
print("Reversed skip elements:", result)

Original list: [1, 2, 3, 4, 5, 6]
Reversed skip elements: [5, 3, 1]


 Exercise on Nested List:

In [57]:
#1. Flatten a Nested List:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
    lst (list): A nested list (list of lists).

    Returns:
    list: A flattened list containing all elements in a single dimension.
    """
    flat_list = []
    for sublist in lst:
        for item in sublist:
            flat_list.append(item)
    return flat_list

nested = [[1, 2], [3, 4], [5]]
result = flatten(nested)

print("Original nested list:", nested)
print("Flattened list:", result)

Original nested list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


In [59]:
#2. Accessing Nested List Elements:
def access_nested_element(lst, indices):
    """
    Accesses a specific element from a nested list using a list of indices.

    Parameters:
    lst (list): The nested list.
    indices (list): A list of indices specifying the path to the element.

    Returns:
    element: The element at the specified indices.
    """
    element = lst
    for idx in indices:
        element = element[idx]
    return element

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)

print("Nested list:", nested_list)
print("Element at indices", indices, ":", result)

Nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Element at indices [1, 2] : 6


In [60]:
#3. Sum of All Elements in a Nested List:
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list, regardless of depth.

    Parameters:
    lst (list): A nested list containing numbers or other lists.

    Returns:
    int/float: The sum of all elements in the nested list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # Recursive call for sublists
        else:
            total += item
    return total

nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)

print("Nested list:", nested_list)
print("Sum of all elements:", result)

Nested list: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


In [61]:
#4. Remove Specific Element from a Nested List:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): A nested list containing elements or other lists.
    elem: The element to remove from the nested list.

    Returns:
    list: A new nested list with all occurrences of elem removed.
    """
    new_list = []
    for item in lst:
        if isinstance(item, list):
            # Recursive call for sublists
            new_list.append(remove_element(item, elem))
        else:
            if item != elem:
                new_list.append(item)
    return new_list

nested_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2
result = remove_element(nested_list, element_to_remove)

print("Original nested list:", nested_list)
print("Modified nested list:", result)

Original nested list: [[1, 2], [3, 2], [4, 5]]
Modified nested list: [[1], [3], [4, 5]]


In [62]:
#5. Find the Maximum Element in a Nested List:
nested_list = [[2, 2], [3, 2], [4, 5]]
element_to_remove = 2
result = remove_element(nested_list, element_to_remove)
print(result)

[[], [3], [4, 5]]


In [63]:
#6. Count Occurrences of an Element in a Nested List:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
    lst (list): A nested list containing elements or other lists.
    elem: The element to count.

    Returns:
    int: The number of occurrences of elem in the nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)  # Recursive call for sublists
        else:
            if item == elem:
                count += 1
    return count

nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
result = count_occurrences(nested_list, element_to_count)

print("Nested list:", nested_list)
print(f"Occurrences of {element_to_count}:", result)

Nested list: [[1, 2], [2, 3], [2, 4]]
Occurrences of 2: 3


In [64]:
#7. Flatten a List of Lists of Lists:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list, regardless of depth.

    Parameters:
    lst (list): A nested list of arbitrary depth.

    Returns:
    list: A flattened list containing all elements in a single dimension.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))  # Recursive call
        else:
            flat_list.append(item)
    return flat_list

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)

print("Original nested list:", nested_list)
print("Flattened list:", result)

Original nested list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


In [65]:
#8. Nested List Average:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
    lst (list): A nested list containing numbers or other lists.

    Returns:
    float: The average of all numbers in the nested list.
    """
    def flatten(lst):
        """Helper function to flatten the nested list."""
        flat_list = []
        for item in lst:
            if isinstance(item, list):
                flat_list.extend(flatten(item))
            else:
                flat_list.append(item)
        return flat_list

    flat_list = flatten(lst)
    if not flat_list:
        return 0  # Avoid division by zero for empty list
    return sum(flat_list) / len(flat_list)

nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)

print("Nested list:", nested_list)
print("Average of all elements:", result)

Nested list: [[1, 2], [3, 4], [5, 6]]
Average of all elements: 3.5


About a Numpy.

In [66]:
import numpy as np
# initialize an all zero array with size 2 X 3:
zeros_arr = np.zeros((2,3))
print(" A zeros array is \n", zeros_arr, "with dimensions", zeros_arr.shape, "\n")

 A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimensions (2, 3) 



In [69]:
import numpy as np
# Create and display zero, one, and n-dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])
for arr in [zero_dim_array, one_dim_array, n_dim_array]:
    print(arr)
    print("Dimensions:", arr.ndim, "Shape:", arr.shape, "\n")

5
Dimensions: 0 Shape: () 

[1 2 3]
Dimensions: 1 Shape: (3,) 

[[1 2]
 [3 4]]
Dimensions: 2 Shape: (2, 2) 



In [70]:
# For a 1-D array:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d.ndim) # Output: 1
# For a 2-D array:
arr_2d = np.array([[1, 2, 3],
[4, 5, 6]])
print(arr_2d.ndim) # Output: 2
#For a 3-D array:
arr_3d = np.array([[[1, 2, 3],
[4, 5, 6]],
[[7, 8, 9],
[10, 11, 12]]])
print(arr_3d.ndim) # Output: 3

1
2
3


In [71]:
print(arr_1d.shape) # Output: (5,)
print(arr_2d.shape) # Output: (2, 3)
print(arr_3d.shape) # Output: (2, 2, 3)

(5,)
(2, 3)
(2, 2, 3)


In [72]:
print(arr_1d.size) # Output: 5
print(arr_2d.size) # Output: 6
print(arr_3d.size) # Output: 12

5
6
12


In [73]:
print(arr_1d.size) # Output: 5
print(arr_2d.size) # Output: 6
print(arr_3d.size) # Output: 12

5
6
12


In [74]:
print(arr_1d.itemsize) # Output: 8 (for int64)

8


In [75]:
print(arr_1d.itemsize) # Output: 8 (for int64)

8


In [76]:
print(arr_2d.T)
# Output:
# [[1 4]
# [2 5]
# [3 6]]

[[1 4]
 [2 5]
 [3 6]]


In [78]:
for item in arr_2d.flat:
    print(item, end=" ") # Output: 1 2 3 4 5 6

1 2 3 4 5 6 

In [79]:
arr_complex = np.array([1+2j, 3+4j])
print(arr_complex.real) # Output: [1. 3.]
print(arr_complex.imag) # Output: [2. 4.]

[1. 3.]
[2. 4.]


In [80]:
arr_float = arr_2d.astype(float)
print(arr_float)
# Output:
# [[1. 2. 3.]
# [4. 5. 6.]]

[[1. 2. 3.]
 [4. 5. 6.]]


In [81]:
import numpy as np
# Create an array with shape (2, 3)
array = np.array([[1, 2, 3],
[4, 5, 6]])

# Reshape to (3, 2), keeping 6 elements
reshaped_array = array.reshape(3, 2)
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)
# Expected Outputs:
# Original Shape: (2, 3)
# Reshaped Shape: (3, 2)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)


In [83]:
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
# Fix: Change the target shape to one that results in 6 elements, e.g., (3, 2).
reshaped_array = array.reshape(3, 2)
print("Original Array:\n", array)
print("Reshaped Array (3,2):\n", reshaped_array)
# The original error was: # Error: cannot reshape array of size 6 into shape (4, 2)

Original Array:
 [[1 2 3]
 [4 5 6]]
Reshaped Array (3,2):
 [[1 2]
 [3 4]
 [5 6]]


How to Create an Array {ndarray}?

In [84]:
#Using in-built function - Arrays with Evenly spaced values:
import numpy as np
a = np.arange(1, 10)
print(a)
x = range(1, 10)
print(x) # x is an iterator
print(list(x))
# further arange examples:
x = np.arange(10.4)
print(x)
x = np.arange(0.5, 10.4, 0.8)
print(x)

[1 2 3 4 5 6 7 8 9]
range(1, 10)
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]


In [86]:
#Creating or Initializing with Ones, Zeros and Empty:
import numpy as np
# Create arrays of specified shapes
ones_array = np.ones((2, 3)) # Shape: (2, 3)
zeros_array = np.zeros((3, 2)) # Shape: (3, 2)
empty_array = np.empty((2, 2)) # Shape: (2, 2)
identity_matrix = np.eye(3) # Shape: (3, 3)
print(ones_array, zeros_array, empty_array, identity_matrix, sep='\n\n')

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[4.24419187e-315 0.00000000e+000]
 [5.08887615e-322             nan]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [88]:
# By Manipulating Existing Array:
import numpy as np
array_from_list = np.array([1, 2, 3]) # [1 2 3]
array_from_tuple = np.array((4, 5, 6)) # [4 5 6]
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]]) # [[1 2 3] [4 5 6]]
print(array_from_list, array_from_tuple, array_from_nested_list, sep='\n')

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]


In [90]:
import numpy as np
# Existing Array of Shape:(2,3)
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Creating Array with Shape of existing array:
zeros, ones, empty = np.zeros(arr.shape), np.ones(arr.shape), np.empty(arr.shape) #
Shape: (2,3)
print(arr, zeros, ones, empty, sep='\n')

[[1 2 3]
 [4 5 6]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[4.22983149e-315 0.00000000e+000 7.78828901e-308]
 [7.56601165e-307 7.56600486e-307 4.45039387e-308]]


In [93]:
#By Combining or joining array:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]]) # Shape: (2, 2)
arr2 = np.array([[5, 6], [7, 8]]) # Shape: (2, 2)
# Stacking examples
hstacked = np.hstack((arr1, arr2))
# Output hstack: [[1 2 5 6] [3 4 7 8]]
vstacked = np.vstack((arr1, arr2))
# Output vstack[[1 2] [3 4] [5 6] [7 8]]
colstacked = np.column_stack((arr1[0], arr2[0]))
# Output column stack: [[1 5] [2 6]]
print(hstacked, vstacked, colstacked, sep='\n')

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 5]
 [2 6]]


In [95]:
import numpy as np
# Creating two 3D arrays
arr1 = np.array([[[1], [2]], [[3], [4]]]) # Shape: (2, 2, 1)
arr2 = np.array([[[5], [6]], [[7], [8]]]) # Shape: (2, 2, 1)
# Concatenate along axis 0 (vertical stacking)
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
# Shape of concat_axis0: (4, 2, 1), arr1 is stacked on top of arr2
# Concatenate along axis 1 (horizontal stacking)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
# Shape of concat_axis1: (2, 4, 1), arr1 and arr2 are placed side by side
# Concatenate along axis 2 (depth stacking)
concat_axis2 = np.concatenate((arr1, arr2), axis=2)
# Shape of concat_axis2: (2, 2, 2), arr1 and arr2 are stacked in depth (third dimension)
# Displaying the results
print("Concatenation along axis 0 (Vertical stacking):\n", concat_axis0)
print("Shape of concatenated array along axis 0:", concat_axis0.shape)
print("\nConcatenation along axis 1 (Horizontal stacking):\n", concat_axis1)
print("Shape of concatenated array along axis 1:", concat_axis1.shape)
print("\nConcatenation along axis 2 (Depth stacking):\n", concat_axis2)
print("Shape of concatenated array along axis 2:", concat_axis2.shape)

Concatenation along axis 0 (Vertical stacking):
 [[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]
Shape of concatenated array along axis 0: (4, 2, 1)

Concatenation along axis 1 (Horizontal stacking):
 [[[1]
  [2]
  [5]
  [6]]

 [[3]
  [4]
  [7]
  [8]]]
Shape of concatenated array along axis 1: (2, 4, 1)

Concatenation along axis 2 (Depth stacking):
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
Shape of concatenated array along axis 2: (2, 2, 2)


Key Errors in Array Combining Operations: Causes and Solutions:

In [97]:
#Error:ValueError: all the input arrays must have same number of dimensions
#Solution
import numpy as np
# Incorrect shapes
arr1 = np.array([[1, 2], [3, 4]]) # shape (2, 2)
arr2 = np.array([5, 6]) # shape (2,)
# Attempting horizontal stack
try:
    hstacked = np.hstack((arr1, arr2)) # Error due to dimension mismatch
except ValueError as e:
    print(f"Error: {e}")
# Solution: Reshape arr2 to match arr1’s dimensions
arr2 = np.array([5, 6]).reshape(2, 1) # shape (2, 1)
hstacked = np.hstack((arr1, arr2)) # No error
print(hstacked)

Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
[[1 2 5]
 [3 4 6]]


In [99]:
#Error:ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)
#Solution
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # shape (2, 3)
arr2 = np.array([[7, 8], [9, 10]]) # shape (2, 2)
# Attempting horizontal stack (this will fail)
try:
    hstacked = np.hstack((arr1, arr2)) # Error due to shape mismatch
except ValueError as e:
    print(f"Error: {e}")
# Solution: Make sure the number of rows in both arrays is the same before stacking
arr2 = np.array([[7, 8, 9], [10, 11, 12]]) # shape (2, 3)
hstacked = np.hstack((arr1, arr2)) # Works fine
print(hstacked)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Array Slicing and Indexing.

In [103]:
import numpy as np
# Creating a 2D array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Accessing elements using indexing
print(array[0, 1]) # Output: 2 (first row, second column)
print(array[-1, -1]) # Output: 9 (last row, last column)
# Slicing the array
print(array[0:2, 1:3]) # Output: [[2, 3], [5, 6]]

2
9
[[2 3]
 [5 6]]


In [105]:
'''import numpy as np
# Creating a 2D array
array = np.array([[1, 2, 3], [4, 5, 6]])
# Attempting to access an element out of bounds
try:
print(array[2, 1])
except IndexError as e:
print(f"Error: {e}")
What does the Error mean?
• The array array has a shape of (2, 3), meaning it has 2 rows and 3 columns.
• When trying to access array[2, 1], you are requesting the third row (index 2), which does not exist
(valid row indices are 0 and 1).
# • This raises an IndexError, as you are trying to access an index outside the valid range of the array.'''

'import numpy as np\n# Creating a 2D array\narray = np.array([[1, 2, 3], [4, 5, 6]])\n# Attempting to access an element out of bounds\ntry:\nprint(array[2, 1])\nexcept IndexError as e:\nprint(f"Error: {e}")\nWhat does the Error mean?\n• The array array has a shape of (2, 3), meaning it has 2 rows and 3 columns.\n• When trying to access array[2, 1], you are requesting the third row (index 2), which does not exist\n(valid row indices are 0 and 1).\n# • This raises an IndexError, as you are trying to access an index outside the valid range of the array.'

In [107]:
import numpy as np
# Example of basic ufuncs: square and square root
arr = np.array([1, 4, 9, 16])
# Square every element
squared = np.square(arr)
# Square root of every element
sqrt = np.sqrt(arr)
print(f"Squared: {squared}")
print(f"Square root: {sqrt}")

Squared: [  1  16  81 256]
Square root: [1. 2. 3. 4.]


In [108]:
import numpy as np
# Trigonometric ufuncs
angles = np.array([0, np.pi / 4, np.pi / 2])
sine_values = np.sin(angles)
# Logarithmic ufuncs
log_values = np.log(arr)

In [109]:
import numpy as np
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
product = np.dot(A, B)
# Compute determinant
det = np.linalg.det(A)
# Compute inverse
inverse = np.linalg.inv(A)
# Compute eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print(f"Matrix Product:\n{product}")
print(f"Determinant: {det}")
print(f"Inverse:\n{inverse}")
print(f"Eigenvalues: {eigvals}, Eigenvectors:\n{eigvecs}")

Matrix Product:
[[19 22]
 [43 50]]
Determinant: -2.0000000000000004
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132], Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [110]:
import numpy as np
A = np.array([[1], [2], [3]]) # Shape (3,1) 3 rows, 1 column
B = np.array([10, 20, 30]) # Shape (3,) 1D array (3 elements)
C = A + B # Works! Result shape: (3,3)
print(C)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [111]:
A = np.array([[1, 2, 3]]) # Shape (1,3)
B = np.array([[4], [5], [6]]) # Shape (3,1)
C = A + B #Works! Result shape: (3,3)
print(C)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


Vectorization:

In [114]:
import numpy as np
import time
# Create two large arrays
size = 10**6
a = np.random.rand(size)
b = np.random.rand(size)
# Using a loop
start_time = time.time()
result_loop = np.zeros(size)
for i in range(size):
    result_loop[i] = a[i] + b[i]
end_time = time.time()
loop_time = end_time - start_time
print(f"Loop Execution Time: {loop_time:.5f} seconds")
# Using NumPy’s vectorized operations
start_time = time.time()
result_vectorized = a + b # Element-wise addition
end_time = time.time()
vectorized_time = end_time - start_time
print(f"Vectorized Execution Time: {vectorized_time:.5f} seconds")
# Performance improvement factor
speedup = loop_time / vectorized_time
print(f"Vectorization is approximately {speedup:.2f} times faster!")

Loop Execution Time: 0.47299 seconds
Vectorized Execution Time: 0.00385 seconds
Vectorization is approximately 122.69 times faster!


10 To - Do - NumPy

In [115]:
#Problem - 1: Array Creation:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty array 2x2:\n", empty_array, "\n")

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("2. All-one array 4x2:\n", ones_array, "\n")

# 3. Return a new array of given shape and type, filled with a fill value
fill_array = np.full((3, 3), fill_value=7, dtype=int)
print("3. Array filled with 7:\n", fill_array, "\n")

# 4. Return a new array of zeros with same shape and type as a given array
given_array = np.array([[5, 6, 7], [8, 9, 10]])
zeros_like_array = np.zeros_like(given_array)
print("4. Zeros like given array:\n", zeros_like_array, "\n")

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("5. Ones like given array:\n", ones_like_array, "\n")

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("6. Numpy array from list:", array_from_list)

1. Empty array 2x2:
 [[1. 2.]
 [3. 4.]] 

2. All-one array 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

3. Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]] 

4. Zeros like given array:
 [[0 0 0]
 [0 0 0]] 

5. Ones like given array:
 [[1 1 1]
 [1 1 1]] 

6. Numpy array from list: [1 2 3 4]


In [116]:
#Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
arr1 = np.arange(10, 50)
print("1. Array from 10 to 49:\n", arr1, "\n")

# 2. Create a 3x3 matrix with values ranging from 0 to 8
arr2 = np.arange(9).reshape(3, 3)
print("2. 3x3 matrix 0-8:\n", arr2, "\n")

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3. 3x3 Identity matrix:\n", identity_matrix, "\n")

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_val = random_array.mean()
print("4. Random array of size 30:\n", random_array)
print("Mean:", mean_val, "\n")

# 5. Create a 10x10 array with random values and find min and max
rand_10x10 = np.random.random((10, 10))
min_val = rand_10x10.min()
max_val = rand_10x10.max()
print("5. 10x10 Random array:\n", rand_10x10)
print("Min:", min_val, "Max:", max_val, "\n")

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Index 4 is the 5th element
print("6. Zero array with 5th element 1:\n", zero_array, "\n")

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("7. Reversed array:\n", reversed_arr, "\n")

# 8. Create a 2D array with 1 on border and 0 inside (5x5 example)
arr8 = np.ones((5, 5))
arr8[1:-1, 1:-1] = 0
print("8. 2D array with border 1 and inside 0:\n", arr8, "\n")

# 9. Create an 8x8 matrix with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("9. 8x8 Checkerboard pattern:\n", checkerboard)

1. Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

2. 3x3 matrix 0-8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

3. 3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

4. Random array of size 30:
 [0.57028991 0.22731424 0.24649747 0.57414492 0.52868103 0.05346267
 0.83558461 0.13689217 0.8681468  0.60603045 0.24737749 0.80230068
 0.30087912 0.8006569  0.99766996 0.59403253 0.79461236 0.73356749
 0.47431649 0.66386898 0.88805762 0.29871268 0.93938867 0.00582316
 0.19499719 0.32211079 0.14378528 0.78582282 0.74779227 0.47012354]
Mean: 0.5284313428739723 

5. 10x10 Random array:
 [[0.98351221 0.97670005 0.13119611 0.11526941 0.91477393 0.78439234
  0.18055585 0.74635787 0.3519713  0.63201414]
 [0.14371109 0.39513372 0.24180442 0.97038729 0.53758756 0.55864114
  0.90154238 0.27852011 0.03188657 0.08837515]
 [0.01666391 0.60991722 0.24267436 0.23259907 0.93625913 0.54896764
  0.94577814 0.3560928

In [117]:
#Problem - 3: Array Operations:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("1. x + y:\n", add_xy, "\n")

# 2. Subtract the two arrays
sub_xy = x - y
print("2. x - y:\n", sub_xy, "\n")

# 3. Multiply the array with an integer (e.g., 3)
mult_x = x * 3
print("3. x * 3:\n", mult_x, "\n")

# 4. Square of each element
square_x = x ** 2
print("4. Square of x:\n", square_x, "\n")

# 5. Dot product
dot_vw = np.dot(v, w)  # dot product of 1D arrays
dot_xv = np.dot(x, v)  # dot product of 2D array and 1D array
dot_xy = np.dot(x, y)  # dot product of 2D arrays
print("5a. Dot product of v and w:", dot_vw)
print("5b. Dot product of x and v:", dot_xv)
print("5c. Dot product of x and y:\n", dot_xy, "\n")

# 6. Concatenate x and y along row (axis=0) and v and w along column (axis=1)
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.column_stack((v, w))  # another way to concatenate 1D arrays as columns
print("6a. Concatenate x and y along rows:\n", concat_xy_row)
print("6b. Concatenate v and w along columns:\n", concat_vw_col, "\n")

# 7. Concatenate x and v (expect an error)
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = e

print("7. Error when concatenating x and v:\n", concat_xv_error)

1. x + y:
 [[ 6  8]
 [10 13]] 

2. x - y:
 [[-4 -4]
 [-4 -3]] 

3. x * 3:
 [[ 3  6]
 [ 9 15]] 

4. Square of x:
 [[ 1  4]
 [ 9 25]] 

5a. Dot product of v and w: 219
5b. Dot product of x and v: [29 77]
5c. Dot product of x and y:
 [[19 22]
 [50 58]] 

6a. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. Concatenate v and w along columns:
 [[ 9 11]
 [10 12]] 

7. Error when concatenating x and v:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:


In [118]:
'''• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.'''

import numpy as np

# Given arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)           # Inverse of A
identity = np.dot(A, A_inv)        # Matrix multiplication
print("1. A * A^-1:\n", identity)
print("Is approximately identity?\n", np.allclose(identity, np.eye(2)), "\n")  # Checks equality with identity

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("2a. AB:\n", AB)
print("2b. BA:\n", BA)
print("AB == BA?", np.array_equal(AB, BA), "\n")  # Should be False

# 3. Prove (AB)^T = B^T * A^T
AB_T = AB.T
BT_AT = np.dot(B.T, A.T)
print("3a. (AB)^T:\n", AB_T)
print("3b. B^T * A^T:\n", BT_AT)
print("Is (AB)^T equal to B^T * A^T?", np.array_equal(AB_T, BT_AT))

1. A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is approximately identity?
 True 

2a. AB:
 [[23 13]
 [51 29]]
2b. BA:
 [[36 44]
 [13 16]]
AB == BA? False 

3a. (AB)^T:
 [[23 51]
 [13 29]]
3b. B^T * A^T:
 [[23 51]
 [13 29]]
Is (AB)^T equal to B^T * A^T? True


In [119]:
"""• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9"""


import numpy as np

# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3,  1, -1]])

# Constant matrix B
B = np.array([-1, -3, 9])

# Step 1: Find inverse of A
A_inv = np.linalg.inv(A)

# Step 2: Solve for X using X = A^-1 * B
X = np.dot(A_inv, B)

print("Solution [x, y, z]:", X)

Solution [x, y, z]: [ 2.  1. -2.]


In [122]:
#Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}
import numpy as np

# Coefficient matrix
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constant vector
B = np.array([-1, -3, 9])

# Compute inverse of A
A_inv = np.linalg.inv(A)

# Multiply inverse with B to find solution
X = np.dot(A_inv, B)

print("Solution using np.linalg.inv():", X)

Solution using np.linalg.inv(): [ 2.  1. -2.]


Experiment: How Fast is Numpy?

In [126]:
#1. Element-wise Addition:
import numpy as np
import time

# Create two large lists of size 1,000,000
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

# --------- Using Python Lists ---------
start_time = time.time()

# Element-wise addition using list comprehension
list_sum = [a + b for a, b in zip(list1, list2)]

end_time = time.time()
print("Time taken using Python lists: {:.6f} seconds".format(end_time - start_time))

# --------- Using NumPy Arrays ---------
# Convert lists to NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

start_time_np = time.time()

# Element-wise addition using NumPy
arr_sum = arr1 + arr2

end_time_np = time.time()
print("Time taken using NumPy arrays: {:.6f} seconds".format(end_time_np - start_time_np))

Time taken using Python lists: 0.056371 seconds
Time taken using NumPy arrays: 0.002485 seconds


In [127]:
#2. Element-wise Multiplication
import numpy as np
import time

# Create two large lists of size 1,000,000
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

# --------- Using Python Lists ---------
start_time = time.time()

# Element-wise multiplication using list comprehension
list_mult = [a * b for a, b in zip(list1, list2)]

end_time = time.time()
print("Time taken using Python lists: {:.6f} seconds".format(end_time - start_time))

# --------- Using NumPy Arrays ---------
# Convert lists to NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

start_time_np = time.time()

# Element-wise multiplication using NumPy
arr_mult = arr1 * arr2

end_time_np = time.time()
print("Time taken using NumPy arrays: {:.6f} seconds".format(end_time_np - start_time_np))

Time taken using Python lists: 0.208147 seconds
Time taken using NumPy arrays: 0.003589 seconds


In [128]:
#3. Dot Product
import numpy as np
import time

# Create two large lists of size 1,000,000
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

# --------- Using Python Lists ---------
start_time = time.time()

# Compute dot product using sum() and list comprehension
dot_list = sum(a * b for a, b in zip(list1, list2))

end_time = time.time()
print("Dot product using Python lists:", dot_list)
print("Time taken using Python lists: {:.6f} seconds".format(end_time - start_time))

# --------- Using NumPy Arrays ---------
# Convert lists to NumPy arrays
arr1 = np.array(list1)
arr2 = np.array(list2)

start_time_np = time.time()

# Compute dot product using np.dot()
dot_np = np.dot(arr1, arr2)

end_time_np = time.time()
print("Dot product using NumPy arrays:", dot_np)
print("Time taken using NumPy arrays: {:.6f} seconds".format(end_time_np - start_time_np))

Dot product using Python lists: 333332833333500000
Time taken using Python lists: 0.169700 seconds
Dot product using NumPy arrays: 333332833333500000
Time taken using NumPy arrays: 0.001689 seconds


In [129]:
#4. Matrix Multiplication
import numpy as np
import time

# Create two 1000x1000 matrices with random integers
rows, cols = 1000, 1000

# Using Python lists
matrix1_list = [[np.random.randint(0, 10) for _ in range(cols)] for _ in range(rows)]
matrix2_list = [[np.random.randint(0, 10) for _ in range(cols)] for _ in range(rows)]

# --------- Matrix Multiplication using Python lists ---------
start_time = time.time()

# Initialize result matrix with zeros
result_list = [[0 for _ in range(cols)] for _ in range(rows)]

# Perform multiplication (triple loop)
for i in range(rows):
    for j in range(cols):
        for k in range(cols):
            result_list[i][j] += matrix1_list[i][k] * matrix2_list[k][j]

end_time = time.time()
print("Time taken using Python lists: {:.6f} seconds".format(end_time - start_time))

# --------- Matrix Multiplication using NumPy arrays ---------
# Create matrices using NumPy
matrix1_np = np.random.randint(0, 10, (rows, cols))
matrix2_np = np.random.randint(0, 10, (rows, cols))

start_time_np = time.time()

# Use NumPy's dot() function
result_np = np.dot(matrix1_np, matrix2_np)

end_time_np = time.time()
print("Time taken using NumPy arrays: {:.6f} seconds".format(end_time_np - start_time_np))

Time taken using Python lists: 209.849812 seconds
Time taken using NumPy arrays: 1.010271 seconds
